/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpeakersRouteImport } from './routes/speakers'
import { Route as RegistrationRouteImport } from './routes/registration'
import { Route as ProgramRouteImport } from './routes/program'
import { Route as GeneralRouteImport } from './routes/general'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DeadlinesRouteImport } from './routes/deadlines'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommitteeRouteImport } from './routes/committee'
import { Route as AbstractsRouteImport } from './routes/abstracts'
import { Route as IndexRouteImport } from './routes/index'

const SpeakersRoute = SpeakersRouteImport.update({
  id: '/speakers',
  path: '/speakers',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationRoute = RegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramRoute = ProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneralRoute = GeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DeadlinesRoute = DeadlinesRouteImport.update({
  id: '/deadlines',
  path: '/deadlines',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitteeRoute = CommitteeRouteImport.update({
  id: '/committee',
  path: '/committee',
  getParentRoute: () => rootRouteImport,
} as any)
const AbstractsRoute = AbstractsRouteImport.update({
  id: '/abstracts',
  path: '/abstracts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abstracts': typeof AbstractsRoute
  '/committee': typeof CommitteeRoute
  '/contact': typeof ContactRoute
  '/deadlines': typeof DeadlinesRoute
  '/gallery': typeof GalleryRoute
  '/general': typeof GeneralRoute
  '/program': typeof ProgramRoute
  '/registration': typeof RegistrationRoute
  '/speakers': typeof SpeakersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abstracts': typeof AbstractsRoute
  '/committee': typeof CommitteeRoute
  '/contact': typeof ContactRoute
  '/deadlines': typeof DeadlinesRoute
  '/gallery': typeof GalleryRoute
  '/general': typeof GeneralRoute
  '/program': typeof ProgramRoute
  '/registration': typeof RegistrationRoute
  '/speakers': typeof SpeakersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abstracts': typeof AbstractsRoute
  '/committee': typeof CommitteeRoute
  '/contact': typeof ContactRoute
  '/deadlines': typeof DeadlinesRoute
  '/gallery': typeof GalleryRoute
  '/general': typeof GeneralRoute
  '/program': typeof ProgramRoute
  '/registration': typeof RegistrationRoute
  '/speakers': typeof SpeakersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abstracts'
    | '/committee'
    | '/contact'
    | '/deadlines'
    | '/gallery'
    | '/general'
    | '/program'
    | '/registration'
    | '/speakers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abstracts'
    | '/committee'
    | '/contact'
    | '/deadlines'
    | '/gallery'
    | '/general'
    | '/program'
    | '/registration'
    | '/speakers'
  id:
    | '__root__'
    | '/'
    | '/abstracts'
    | '/committee'
    | '/contact'
    | '/deadlines'
    | '/gallery'
    | '/general'
    | '/program'
    | '/registration'
    | '/speakers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbstractsRoute: typeof AbstractsRoute
  CommitteeRoute: typeof CommitteeRoute
  ContactRoute: typeof ContactRoute
  DeadlinesRoute: typeof DeadlinesRoute
  GalleryRoute: typeof GalleryRoute
  GeneralRoute: typeof GeneralRoute
  ProgramRoute: typeof ProgramRoute
  RegistrationRoute: typeof RegistrationRoute
  SpeakersRoute: typeof SpeakersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/speakers': {
      id: '/speakers'
      path: '/speakers'
      fullPath: '/speakers'
      preLoaderRoute: typeof SpeakersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program': {
      id: '/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/general': {
      id: '/general'
      path: '/general'
      fullPath: '/general'
      preLoaderRoute: typeof GeneralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deadlines': {
      id: '/deadlines'
      path: '/deadlines'
      fullPath: '/deadlines'
      preLoaderRoute: typeof DeadlinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/committee': {
      id: '/committee'
      path: '/committee'
      fullPath: '/committee'
      preLoaderRoute: typeof CommitteeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abstracts': {
      id: '/abstracts'
      path: '/abstracts'
      fullPath: '/abstracts'
      preLoaderRoute: typeof AbstractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbstractsRoute: AbstractsRoute,
  CommitteeRoute: CommitteeRoute,
  ContactRoute: ContactRoute,
  DeadlinesRoute: DeadlinesRoute,
  GalleryRoute: GalleryRoute,
  GeneralRoute: GeneralRoute,
  ProgramRoute: ProgramRoute,
  RegistrationRoute: RegistrationRoute,
  SpeakersRoute: SpeakersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
